type Query {
  getGBooks: [Book]!
  getBooks(uid: Int): [BookUser]!
  getBook(bid: Int): BookUser
  getReqsByBook(bid: Int!, all: Boolean = false): [BookUser]!
  getReqsByUser(rid: Int!, all: Boolean = false): [BookUser]!
  getUserReqs(uid: Int!, all: Boolean = false): [BookUser]!
  getUserDetail(id: Int!): User # will not return email, token
  getGGAPI: String!
}

type Mutation {
  signup(name: String!, email: String!, loc: String, pw: String!): User
  login(email: String!, pw: String!): User
  loginWithToken(token: String!): User
  logout(token: String!): Int

  updateDetail(token: String!, key: UserDetail!, value: String!): Int!

  addBook(token: String!, gid: String!): BookUser!
  delBook(token: String!, bid: Int!): Int!
  tradeBook(token: String!, type: TradeType!, bid: Int!, rid: Int): Int!
}

type Book {
  id: Int!
  gid: String!
}

type BookUser {
  id: Int!
  bid: Int!
  uid: Int
  rid: Int
  status: Int
  ts: Int
}

type User {
  id: Int!
  name: String
  email: String!
  loc: String
  token: String!
}

enum UserDetail {
  name
  loc
  email
  pw
}

enum TradeType {
  request
  accept
  decline
}
